// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ModelGeneratorConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=115.29.250.241;Initial Catalog=WeiXinTicketSys;User ID=sa;Password=80Piao123`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LambdaSqlBuilder;
using WeiXinTicketSystem.Entity.Enum;

namespace WeiXinTicketSystem.Entity.Models
{
    /// <summary>
    /// A class which represents the ConponGroup table.
    /// </summary>
    [Table("ConponGroup")]
    [SqlLamTable(Name = "ConponGroup")]
    public partial class ConponGroupEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual string GroupName { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual int? ConponNumber { get; set; }
		public virtual string SnackOrFilmCode { get; set; }
		public virtual DateTime? ValidityDate { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual string Remark { get; set; }
	}

    /// <summary>
    /// A class which represents the Conpons table.
    /// </summary>
    [Table("Conpons")]
    [SqlLamTable(Name = "Conpons")]
    public partial class ConponEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string TypeName { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual string ConponCode { get; set; }
		public virtual string SnackCode { get; set; }
		public virtual DateTime? ValidityDate { get; set; }
		public virtual DateTime? ReceivedDate { get; set; }
		public virtual ConponStatusEnum Status { get; set; }
		public virtual DateTime? UseDate { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string Title { get; set; }
		public virtual string Remark { get; set; }
	}

    /// <summary>
    /// A class which represents the ConponGroupView view.
    /// </summary>
    [Table("ConponGroupView")]
    [SqlLamTable(Name = "ConponGroupView")]
    public partial class ConponGroupViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string TypeName { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual string GroupName { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual int? ConponNumber { get; set; }
		public virtual string SnackOrFilmCode { get; set; }
		public virtual DateTime? ValidityDate { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual int? UsedNumber { get; set; }
		public virtual int? NotUsedNumber { get; set; }
		public virtual int? ReceivedNumber { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string Remark { get; set; }
	}

    /// <summary>
    /// A class which represents the GivingConditions table.
    /// </summary>
    [Table("GivingConditions")]
    [SqlLamTable(Name = "GivingConditions")]
    public partial class GivingConditionEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string Conditions { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual int? Number { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string Remark { get; set; }
	}

    /// <summary>
    /// A class which represents the SessionInfo table.
    /// </summary>
    [Table("SessionInfo")]
    [SqlLamTable(Name = "SessionInfo")]
    public partial class SessionInfoEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CCode { get; set; }
		public virtual string SCode { get; set; }
		public virtual string ScreenCode { get; set; }
		public virtual DateTime StartTime { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual int? Duration { get; set; }
		public virtual string Language { get; set; }
		public virtual DateTime? UpdateTime { get; set; }
		public virtual decimal StandardPrice { get; set; }
		public virtual decimal LowestPrice { get; set; }
		public virtual decimal SettlePrice { get; set; }
		public virtual decimal TicketFee { get; set; }
		public virtual bool? IsAvalible { get; set; }
		public virtual string PlaythroughFlag { get; set; }
		public virtual string Dimensional { get; set; }
		public virtual int Sequence { get; set; }
		public virtual int UserID { get; set; }
		public virtual string DingXinUpdateTime { get; set; }
		public virtual decimal? ListingPrice { get; set; }
		public virtual string FeatureNo { get; set; }
		public virtual string YueKeSaleStatus { get; set; }
		public virtual DateTime? YueKeStopSellingTime { get; set; }
		public virtual string YueKeScheduleId { get; set; }
		public virtual string YueKeScheduleKey { get; set; }
		public virtual int? VistaLayoutId { get; set; }
		public virtual decimal? VistaThresholds { get; set; }
	}

    /// <summary>
    /// A class which represents the SnackOrderDetailsView view.
    /// </summary>
    [Table("SnackOrderDetailsView")]
    [SqlLamTable(Name = "SnackOrderDetailsView")]
    public partial class SnackOrderDetailsViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual int OrderId { get; set; }
		public virtual string SnackCode { get; set; }
		public virtual string SnackName { get; set; }
		public virtual decimal StandardPrice { get; set; }
		public virtual decimal SalePrice { get; set; }
		public virtual int Number { get; set; }
		public virtual decimal SubTotalPrice { get; set; }
		public virtual decimal? ActualPrice { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual string ConponCode { get; set; }
		public virtual string Title { get; set; }
		public virtual decimal? ConponPrice { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OrderCode { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual int SnacksCount { get; set; }
		public virtual decimal TotalPrice { get; set; }
		public virtual DateTime? ReleaseTime { get; set; }
		public virtual DateTime? SubmitTime { get; set; }
		public virtual string VoucherCode { get; set; }
		public virtual SnackOrderStatusEnum OrderStatus { get; set; }
		public virtual DateTime? RefundTime { get; set; }
		public virtual DateTime? FetchTime { get; set; }
		public virtual string DeliveryAddress { get; set; }
		public virtual DateTime SendTime { get; set; }
		public virtual bool? OrderPayFlag { get; set; }
		public virtual byte? OrderPayType { get; set; }
		public virtual DateTime? OrderPayTime { get; set; }
		public virtual string OrderTradeNo { get; set; }
		public virtual bool? IsUseConpons { get; set; }
		public virtual string CinemaName { get; set; }
	}

    /// <summary>
    /// A class which represents the UserInfo table.
    /// </summary>
    [Table("UserInfo")]
    [SqlLamTable(Name = "UserInfo")]
    public partial class UserInfoEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string Company { get; set; }
		public virtual string Address { get; set; }
		public virtual string Tel { get; set; }
		public virtual int? Advance { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual DateTime? BeginDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
	}

    /// <summary>
    /// A class which represents the User_Cinema table.
    /// </summary>
    [Table("User_Cinema")]
    [SqlLamTable(Name = "User_Cinema")]
    public partial class UserCinemaEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual int UserId { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual decimal? Fee { get; set; }
		public virtual decimal? CinemaFee { get; set; }
		public virtual string PayType { get; set; }
		public virtual decimal? RealPrice { get; set; }
		public virtual DateTime? ExpDate { get; set; }
		public virtual SnackInterfaceEnum OpenSnacks { get; set; }
	}

    /// <summary>
    /// A class which represents the Middleware table.
    /// </summary>
    [Table("Middleware")]
    [SqlLamTable(Name = "Middleware")]
    public partial class MiddlewareEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string Title { get; set; }
		public virtual string Url { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual CinemaTypeEnum Type { get; set; }
		public virtual int? CinemaCount { get; set; }
		public virtual int? IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the FilmComments table.
    /// </summary>
    [Table("FilmComments")]
    [SqlLamTable(Name = "FilmComments")]
    public partial class FilmCommentEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual decimal Score { get; set; }
		public virtual string CommentContent { get; set; }
		public virtual string OpenID { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual bool Deleted { get; set; }
	}

    /// <summary>
    /// A class which represents the ScreenSeatInfo table.
    /// </summary>
    [Table("ScreenSeatInfo")]
    [SqlLamTable(Name = "ScreenSeatInfo")]
    public partial class ScreenSeatInfoEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string ScreenCode { get; set; }
		public virtual string SeatCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual string RowNum { get; set; }
		public virtual string ColumnNum { get; set; }
		public virtual int XCoord { get; set; }
		public virtual int YCoord { get; set; }
		public virtual string Status { get; set; }
		public virtual string LoveFlag { get; set; }
		public virtual string Type { get; set; }
		public virtual DateTime UpdateTime { get; set; }
		public virtual int? VistaLayoutId { get; set; }
		public virtual string DY1905SeatCode { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminActivityPopupView view.
    /// </summary>
    [Table("AdminActivityPopupView")]
    [SqlLamTable(Name = "AdminActivityPopupView")]
    public partial class AdminActivityPopupViewEntity : EntityBase
    {
		public virtual string CinemaCode { get; set; }
		public virtual string GradeCode { get; set; }
		public virtual string Image { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string GradeName { get; set; }
		public virtual int Id { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual ActivityPopupEnum Popup { get; set; }
	}

    /// <summary>
    /// A class which represents the ScreenInfo table.
    /// </summary>
    [Table("ScreenInfo")]
    [SqlLamTable(Name = "ScreenInfo")]
    public partial class ScreenInfoEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CCode { get; set; }
		public virtual string SCode { get; set; }
		public virtual string SName { get; set; }
		public virtual DateTime? UpdateTime { get; set; }
		public virtual int? SeatCount { get; set; }
		public virtual string Type { get; set; }
		public virtual string VistaLayoutId { get; set; }
		public virtual string DY1905ScreenCode { get; set; }
	}

    /// <summary>
    /// A class which represents the PricePlan table.
    /// </summary>
    [Table("PricePlan")]
    [SqlLamTable(Name = "PricePlan")]
    public partial class PricePlanEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string Code { get; set; }
		public virtual int UserID { get; set; }
		public virtual decimal Price { get; set; }
		public virtual PricePlanTypeEnum Type { get; set; }
	}

    /// <summary>
    /// A class which represents the ActivityPopup table.
    /// </summary>
    [Table("ActivityPopup")]
    [SqlLamTable(Name = "ActivityPopup")]
    public partial class ActivityPopupEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual ActivityPopupEnum Popup { get; set; }
		public virtual string GradeCode { get; set; }
		public virtual string Image { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the OrderSeatDetails table.
    /// </summary>
    [Table("OrderSeatDetails")]
    [SqlLamTable(Name = "OrderSeatDetails")]
    public partial class OrderSeatDetailEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual int OrderId { get; set; }
		public virtual string SeatCode { get; set; }
		public virtual string RowNum { get; set; }
		public virtual string ColumnNum { get; set; }
		public virtual decimal Price { get; set; }
		public virtual decimal SalePrice { get; set; }
		public virtual decimal Fee { get; set; }
		public virtual string FilmTicketCode { get; set; }
		public virtual string TicketInfoCode { get; set; }
		public virtual byte? PrintFlag { get; set; }
		public virtual string YkSeatCode { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaPriceSettings table.
    /// </summary>
    [Table("CinemaPriceSettings")]
    [SqlLamTable(Name = "CinemaPriceSettings")]
    public partial class CinemaPriceSettingEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual int? WeChatDiscount { get; set; }
		public virtual decimal FackPriceUpperLimit { get; set; }
		public virtual YesOrNoEnum? IsSellByStandardPrice { get; set; }
		public virtual decimal? LoveSeatPriceDifferences { get; set; }
		public virtual decimal Fee { get; set; }
		public virtual decimal MemberFee { get; set; }
		public virtual CinemaFeePayTypeEnum FeePayType { get; set; }
		public virtual CinemaFeeGatherTypeEnum FeeGatherType { get; set; }
	}

    /// <summary>
    /// A class which represents the MemberCard table.
    /// </summary>
    [Table("MemberCard")]
    [SqlLamTable(Name = "MemberCard")]
    public partial class MemberCardEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual string CardNo { get; set; }
		public virtual string CardPassword { get; set; }
		public virtual decimal? Balance { get; set; }
		public virtual int? Score { get; set; }
		public virtual string LevelCode { get; set; }
		public virtual string LevelName { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Sex { get; set; }
		public virtual string CreditNum { get; set; }
		public virtual DateTime? Birthday { get; set; }
		public virtual DateTime? ExpireDate { get; set; }
		public virtual DateTime? CreateTime { get; set; }
		public virtual MemberCardStatusEnum Status { get; set; }
		public virtual DateTime? Updated { get; set; }
	}

    /// <summary>
    /// A class which represents the MemberCardLevel table.
    /// </summary>
    [Table("MemberCardLevel")]
    [SqlLamTable(Name = "MemberCardLevel")]
    public partial class MemberCardLevelEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string LevelCode { get; set; }
		public virtual string LevelName { get; set; }
	}

    /// <summary>
    /// A class which represents the Cinema table.
    /// </summary>
    [Table("Cinema")]
    [SqlLamTable(Name = "Cinema")]
    public partial class CinemaEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual int MId { get; set; }
		public virtual string Code { get; set; }
		public virtual string Name { get; set; }
		public virtual string Address { get; set; }
		public virtual int? ScreenCount { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual int? ManualAdd { get; set; }
		public virtual int? DingXinId { get; set; }
		public virtual string YueKeId { get; set; }
		public virtual CinemaOpenEnum IsOpen { get; set; }
		public virtual string DY1905Id { get; set; }
		public virtual string ContactName { get; set; }
		public virtual string ContactMobile { get; set; }
		public virtual TheaterChainEnum TheaterChain { get; set; }
		public virtual double? Latitude { get; set; }
		public virtual double? Longitude { get; set; }
		public virtual CinemaOpenEnum IsOpenSnacks { get; set; }
		public virtual string CinemaPhone { get; set; }
		public virtual string TicketHint { get; set; }
		public virtual string CinemaLabel { get; set; }
		public virtual YesOrNoEnum? IsSnackDistribution { get; set; }
		public virtual string CardNo { get; set; }
		public virtual string CardPassword { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
	}

    /// <summary>
    /// A class which represents the MemberChargeSetting table.
    /// </summary>
    [Table("MemberChargeSetting")]
    [SqlLamTable(Name = "MemberChargeSetting")]
    public partial class MemberChargeSettingEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual int? Number { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string Remark { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminMemberChargeSettingView view.
    /// </summary>
    [Table("AdminMemberChargeSettingView")]
    [SqlLamTable(Name = "AdminMemberChargeSettingView")]
    public partial class AdminMemberChargeSettingViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual int? Number { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string Remark { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string GroupName { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaWeChatOfficialAccounts table.
    /// </summary>
    [Table("CinemaWeChatOfficialAccounts")]
    [SqlLamTable(Name = "CinemaWeChatOfficialAccounts")]
    public partial class CinemaWeChatOfficialAccountEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string OriginalID { get; set; }
		public virtual string Token { get; set; }
		public virtual string AppId { get; set; }
		public virtual string AppSecret { get; set; }
		public virtual string Micro_signal { get; set; }
		public virtual WeChatOfficialAccountTypeEnum? AccountType { get; set; }
		public virtual string vice_OriginalID { get; set; }
		public virtual string vice_Token { get; set; }
		public virtual string vice_AppId { get; set; }
		public virtual string vice_AppSecret { get; set; }
		public virtual string vice_Micro_signal { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminFilmCommentView view.
    /// </summary>
    [Table("AdminFilmCommentView")]
    [SqlLamTable(Name = "AdminFilmCommentView")]
    public partial class AdminFilmCommentViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual decimal Score { get; set; }
		public virtual string CommentContent { get; set; }
		public virtual string OpenID { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string NickName { get; set; }
		public virtual string HeadImgUrl { get; set; }
	}

    /// <summary>
    /// A class which represents the Orders table.
    /// </summary>
    [Table("Orders")]
    [SqlLamTable(Name = "Orders")]
    public partial class OrderEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual int UserId { get; set; }
		public virtual string SessionCode { get; set; }
		public virtual string ScreenCode { get; set; }
		public virtual DateTime SessionTime { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual int TicketCount { get; set; }
		public virtual decimal TotalPrice { get; set; }
		public virtual decimal TotalFee { get; set; }
		public virtual decimal TotalSalePrice { get; set; }
		public virtual OrderStatusEnum OrderStatus { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual DateTime? LockTime { get; set; }
		public virtual DateTime? AutoUnlockDatetime { get; set; }
		public virtual string LockOrderCode { get; set; }
		public virtual DateTime? SubmitTime { get; set; }
		public virtual string SubmitOrderCode { get; set; }
		public virtual string PrintNo { get; set; }
		public virtual string VerifyCode { get; set; }
		public virtual YesOrNoEnum? PrintStatus { get; set; }
		public virtual DateTime? PrintTime { get; set; }
		public virtual DateTime? RefundTime { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string ErrorMessage { get; set; }
		public virtual string SerialNum { get; set; }
		public virtual bool IsMemberPay { get; set; }
		public virtual string PayType { get; set; }
		public virtual string Printpassword { get; set; }
		public virtual string PaySeqNo { get; set; }
		public virtual decimal? TotalLoveSeatDifferences { get; set; }
		public virtual CinemaFeePayTypeEnum? FeePayType { get; set; }
		public virtual decimal? TotalGuestPayFee { get; set; }
		public virtual string RefundTradeNo { get; set; }
		public virtual byte? PayFlag { get; set; }
		public virtual PayTypeEnum? OrderPayType { get; set; }
		public virtual DateTime? PayTime { get; set; }
		public virtual string OrderTradeNo { get; set; }
		public virtual string CardNo { get; set; }
		public virtual string OpenID { get; set; }
		public virtual string IDCardNumber { get; set; }
	}

    /// <summary>
    /// A class which represents the SystemMenuView view.
    /// </summary>
    [Table("SystemMenuView")]
    [SqlLamTable(Name = "SystemMenuView")]
    public partial class SystemMenuViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual int RoleId { get; set; }
		public virtual string Permissions { get; set; }
		public virtual string ModuleName { get; set; }
		public virtual string ModuleIcon { get; set; }
		public virtual int ModuleId { get; set; }
		public virtual int ModuleParentId { get; set; }
		public virtual int? ModuleSequence { get; set; }
		public virtual string ModuleFlag { get; set; }
	}

    /// <summary>
    /// A class which represents the FilmInfo table.
    /// </summary>
    [Table("FilmInfo")]
    [SqlLamTable(Name = "FilmInfo")]
    public partial class FilmInfoEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual string Version { get; set; }
		public virtual string Duration { get; set; }
		public virtual DateTime? PublishDate { get; set; }
		public virtual string Publisher { get; set; }
		public virtual string Producer { get; set; }
		public virtual string Director { get; set; }
		public virtual string Cast { get; set; }
		public virtual string Introduction { get; set; }
		public virtual decimal? Score { get; set; }
		public virtual string Area { get; set; }
		public virtual string Type { get; set; }
		public virtual string Language { get; set; }
		public virtual FilmStatusEnum Status { get; set; }
		public virtual string Image { get; set; }
		public virtual string Trailer { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaMemberCardSettings table.
    /// </summary>
    [Table("CinemaMemberCardSettings")]
    [SqlLamTable(Name = "CinemaMemberCardSettings")]
    public partial class CinemaMemberCardSettingEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual YesOrNoEnum IsCardUse { get; set; }
		public virtual YesOrNoEnum IsCardRegister { get; set; }
		public virtual YesOrNoEnum IsCardReCharge { get; set; }
		public virtual MemberCardTypeEnum CardType { get; set; }
		public virtual string ThirdMemberUrl { get; set; }
		public virtual string InitialCardPassword { get; set; }
		public virtual int? OscarDiscount { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaPrintSettings table.
    /// </summary>
    [Table("CinemaPrintSettings")]
    [SqlLamTable(Name = "CinemaPrintSettings")]
    public partial class CinemaPrintSettingEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual YesOrNoEnum IsPrintName { get; set; }
		public virtual YesOrNoEnum IsCustomTicketTemplet { get; set; }
		public virtual YesOrNoEnum IsCustomPackageTemplet { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaView view.
    /// </summary>
    [Table("CinemaView")]
    [SqlLamTable(Name = "CinemaView")]
    public partial class CinemaViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual int MId { get; set; }
		public virtual string Code { get; set; }
		public virtual string Name { get; set; }
		public virtual string Address { get; set; }
		public virtual int? ScreenCount { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual int? ManualAdd { get; set; }
		public virtual int? DingXinId { get; set; }
		public virtual string DY1905Id { get; set; }
		public virtual string ContactName { get; set; }
		public virtual string ContactMobile { get; set; }
		public virtual TheaterChainEnum TheaterChain { get; set; }
		public virtual double? Latitude { get; set; }
		public virtual double? Longitude { get; set; }
		public virtual CinemaOpenEnum IsOpenSnacks { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual CinemaOpenEnum IsOpen { get; set; }
		public virtual CinemaTypeEnum CinemaType { get; set; }
		public virtual string CinemaPhone { get; set; }
		public virtual string TicketHint { get; set; }
		public virtual string CinemaLabel { get; set; }
		public virtual YesOrNoEnum? IsSnackDistribution { get; set; }
	}

    /// <summary>
    /// A class which represents the ScoreRecords table.
    /// </summary>
    [Table("ScoreRecords")]
    [SqlLamTable(Name = "ScoreRecords")]
    public partial class ScoreRecordEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual ScoreRecordTypeEnum Type { get; set; }
		public virtual int? Score { get; set; }
		public virtual string Description { get; set; }
		public virtual ScoreRecordDirectionEnum Direction { get; set; }
		public virtual DateTime? Created { get; set; }
	}

    /// <summary>
    /// A class which represents the SystemUsers table.
    /// </summary>
    [Table("SystemUsers")]
    [SqlLamTable(Name = "SystemUsers")]
    public partial class SystemUserEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string RealName { get; set; }
		public virtual int RoleId { get; set; }
		public virtual string RoleName { get; set; }
		public virtual int? CreateUserId { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual int? UpdateUserId { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
	}

    /// <summary>
    /// A class which represents the UserStamps table.
    /// </summary>
    [Table("UserStamps")]
    [SqlLamTable(Name = "UserStamps")]
    public partial class UserStampEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual string StampCode { get; set; }
		public virtual UserStampCollectTypeEnum CollectType { get; set; }
		public virtual UserStampStatusEnum Status { get; set; }
		public virtual DateTime? Created { get; set; }
	}

    /// <summary>
    /// A class which represents the TicketUsers table.
    /// </summary>
    [Table("TicketUsers")]
    [SqlLamTable(Name = "TicketUsers")]
    public partial class TicketUserEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual string OpenID { get; set; }
		public virtual string VerifyCode { get; set; }
		public virtual YesOrNoEnum IsActive { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual string NickName { get; set; }
		public virtual UserSexEnum Sex { get; set; }
		public virtual string Country { get; set; }
		public virtual string Province { get; set; }
		public virtual string City { get; set; }
		public virtual string HeadImgUrl { get; set; }
		public virtual long? TotalScore { get; set; }
		public virtual string Language { get; set; }
	}

    /// <summary>
    /// A class which represents the SystemRoles table.
    /// </summary>
    [Table("SystemRoles")]
    [SqlLamTable(Name = "SystemRoles")]
    public partial class SystemRoleEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual SystemRoleTypeEnum? Type { get; set; }
		public virtual int? CreateUserId { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
	}

    /// <summary>
    /// A class which represents the SystemRolePermissionsView view.
    /// </summary>
    [Table("SystemRolePermissionsView")]
    [SqlLamTable(Name = "SystemRolePermissionsView")]
    public partial class SystemRolePermissionsViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual int? RoleId { get; set; }
		public virtual string RoleName { get; set; }
		public virtual string ModuleName { get; set; }
		public virtual string Permissions { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaMiniProgramAccounts table.
    /// </summary>
    [Table("CinemaMiniProgramAccounts")]
    [SqlLamTable(Name = "CinemaMiniProgramAccounts")]
    public partial class CinemaMiniProgramAccountEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string AppId { get; set; }
		public virtual string AppSecret { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the SystemRolePermissions table.
    /// </summary>
    [Table("SystemRolePermissions")]
    [SqlLamTable(Name = "SystemRolePermissions")]
    public partial class SystemRolePermissionEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual int RoleId { get; set; }
		public virtual int ModuleId { get; set; }
		public virtual string Permissions { get; set; }
	}

    /// <summary>
    /// A class which represents the Banner table.
    /// </summary>
    [Table("Banner")]
    [SqlLamTable(Name = "Banner")]
    public partial class BannerEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string Title { get; set; }
		public virtual string Image { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual string LinkUrl { get; set; }
		public virtual YesOrNoEnum Status { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminSnacksView view.
    /// </summary>
    [Table("AdminSnacksView")]
    [SqlLamTable(Name = "AdminSnacksView")]
    public partial class AdminSnacksViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string SnackCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string TypeName { get; set; }
		public virtual string SnackName { get; set; }
		public virtual string Remark { get; set; }
		public virtual decimal StandardPrice { get; set; }
		public virtual decimal SalePrice { get; set; }
		public virtual SnackStatusEnum Status { get; set; }
		public virtual int Stock { get; set; }
		public virtual DateTime? ExpDate { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual YesOrNoEnum IsRecommand { get; set; }
		public virtual string Image { get; set; }
		public virtual string CinemaName { get; set; }
	}

    /// <summary>
    /// A class which represents the ApiUserStampView view.
    /// </summary>
    [Table("ApiUserStampView")]
    [SqlLamTable(Name = "ApiUserStampView")]
    public partial class ApiUserStampViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual string StampCode { get; set; }
		public virtual UserStampCollectTypeEnum CollectType { get; set; }
		public virtual UserStampStatusEnum Status { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual string Title { get; set; }
		public virtual string Image { get; set; }
		public virtual DateTime? ValidityDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SnackTypes table.
    /// </summary>
    [Table("SnackTypes")]
    [SqlLamTable(Name = "SnackTypes")]
    public partial class SnackTypeEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string TypeName { get; set; }
		public virtual string Remark { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual string Image { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminSnackTypesView view.
    /// </summary>
    [Table("AdminSnackTypesView")]
    [SqlLamTable(Name = "AdminSnackTypesView")]
    public partial class AdminSnackTypesViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string TypeName { get; set; }
		public virtual string Image { get; set; }
		public virtual int? SnacksCount { get; set; }
		public virtual string Remark { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual string Expr1 { get; set; }
	}

    /// <summary>
    /// A class which represents the Snacks table.
    /// </summary>
    [Table("Snacks")]
    [SqlLamTable(Name = "Snacks")]
    public partial class SnackEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string SnackCode { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string SnackName { get; set; }
		public virtual string Remark { get; set; }
		public virtual decimal StandardPrice { get; set; }
		public virtual decimal SalePrice { get; set; }
		public virtual SnackStatusEnum Status { get; set; }
		public virtual int Stock { get; set; }
		public virtual DateTime? ExpDate { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual YesOrNoEnum IsRecommand { get; set; }
		public virtual string Image { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminSnackOrdersView view.
    /// </summary>
    [Table("AdminSnackOrdersView")]
    [SqlLamTable(Name = "AdminSnackOrdersView")]
    public partial class AdminSnackOrdersViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OrderCode { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual int SnacksCount { get; set; }
		public virtual decimal TotalPrice { get; set; }
		public virtual DateTime? SubmitTime { get; set; }
		public virtual string VoucherCode { get; set; }
		public virtual SnackOrderStatusEnum OrderStatus { get; set; }
		public virtual DateTime? RefundTime { get; set; }
		public virtual DateTime? FetchTime { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual string DeliveryAddress { get; set; }
		public virtual DateTime SendTime { get; set; }
		public virtual bool? OrderPayFlag { get; set; }
		public virtual byte? OrderPayType { get; set; }
		public virtual DateTime? OrderPayTime { get; set; }
		public virtual string OrderTradeNo { get; set; }
		public virtual bool? IsUseConpons { get; set; }
		public virtual string ConponCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual decimal? ConponPrice { get; set; }
	}

    /// <summary>
    /// A class which represents the DefaultActions table.
    /// </summary>
    [Table("DefaultActions")]
    [SqlLamTable(Name = "DefaultActions")]
    public partial class DefaultActionEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string ActionName { get; set; }
		public virtual DefaultActionTypeEnum? ActionType { get; set; }
		public virtual string ActionNewsTitle { get; set; }
		public virtual string ActionNewsCover { get; set; }
		public virtual string ActionNewsDesc { get; set; }
		public virtual string ActionUrl { get; set; }
		public virtual bool? IsActive { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaCustomMenu table.
    /// </summary>
    [Table("CinemaCustomMenu")]
    [SqlLamTable(Name = "CinemaCustomMenu")]
    public partial class CinemaCustomMenuEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string MenuName { get; set; }
		public virtual CustomMenuTypeEnum? MenuType { get; set; }
		public virtual string MenuKey { get; set; }
		public virtual string MenuUrl { get; set; }
		public virtual int? MenuParentId { get; set; }
		public virtual int? MenuSequence { get; set; }
		public virtual CustomMenuReTypeEnum? MenuReType { get; set; }
		public virtual string MenuReText { get; set; }
		public virtual int? MenuReArticleID { get; set; }
		public virtual bool? IsActive { get; set; }
		public virtual bool? IsPublish { get; set; }
		public virtual DateTime? PublishTime { get; set; }
		public virtual int? MenuDefaultActionId { get; set; }
	}

    /// <summary>
    /// A class which represents the SystemModule table.
    /// </summary>
    [Table("SystemModule")]
    [SqlLamTable(Name = "SystemModule")]
    public partial class SystemModuleEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string ModuleName { get; set; }
		public virtual string ModuleIcon { get; set; }
		public virtual int ModuleParentId { get; set; }
		public virtual int? ModuleSequence { get; set; }
		public virtual string ModuleFlag { get; set; }
		public virtual int? CreateUserId { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
	}

    /// <summary>
    /// A class which represents the MiniProgramLinkUrl table.
    /// </summary>
    [Table("MiniProgramLinkUrl")]
    [SqlLamTable(Name = "MiniProgramLinkUrl")]
    public partial class MiniProgramLinkUrlEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string LinkName { get; set; }
		public virtual string LinkUrl { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminGivingConditionsView view.
    /// </summary>
    [Table("AdminGivingConditionsView")]
    [SqlLamTable(Name = "AdminGivingConditionsView")]
    public partial class AdminGivingConditionsViewEntity : EntityBase
    {
		public virtual string CinemaCode { get; set; }
		public virtual int Id { get; set; }
		public virtual string Conditions { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual DateTime? Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual int? Number { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual string GroupName { get; set; }
		public virtual string Remark { get; set; }
	}

    /// <summary>
    /// A class which represents the RecommendGrade table.
    /// </summary>
    [Table("RecommendGrade")]
    [SqlLamTable(Name = "RecommendGrade")]
    public partial class RecommendGradeEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string GradeCode { get; set; }
		public virtual string GradeName { get; set; }
		public virtual string Remark { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the Stamps table.
    /// </summary>
    [Table("Stamps")]
    [SqlLamTable(Name = "Stamps")]
    public partial class StampEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string Title { get; set; }
		public virtual string StampCode { get; set; }
		public virtual string Image { get; set; }
		public virtual DateTime? ValidityDate { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
	}

    /// <summary>
    /// A class which represents the Activity table.
    /// </summary>
    [Table("Activity")]
    [SqlLamTable(Name = "Activity")]
    public partial class ActivityEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string Title { get; set; }
		public virtual string Image { get; set; }
		public virtual string ActivityContent { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual string LinkUrl { get; set; }
		public virtual string GradeCode { get; set; }
		public virtual int? ActivitySequence { get; set; }
		public virtual YesOrNoEnum Status { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminMemberCardView view.
    /// </summary>
    [Table("AdminMemberCardView")]
    [SqlLamTable(Name = "AdminMemberCardView")]
    public partial class AdminMemberCardViewEntity : EntityBase
    {
		public virtual string NickName { get; set; }
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual string CardNo { get; set; }
		public virtual string CardPassword { get; set; }
		public virtual decimal? Balance { get; set; }
		public virtual int? Score { get; set; }
		public virtual string LevelCode { get; set; }
		public virtual MemberCardStatusEnum Status { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual string MobilePhone { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminActivityView view.
    /// </summary>
    [Table("AdminActivityView")]
    [SqlLamTable(Name = "AdminActivityView")]
    public partial class AdminActivityViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string Title { get; set; }
		public virtual string Image { get; set; }
		public virtual string ActivityContent { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual string LinkUrl { get; set; }
		public virtual string GradeCode { get; set; }
		public virtual int? ActivitySequence { get; set; }
		public virtual YesOrNoEnum Status { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual string GradeName { get; set; }
		public virtual string LinkName { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminConponView view.
    /// </summary>
    [Table("AdminConponView")]
    [SqlLamTable(Name = "AdminConponView")]
    public partial class AdminConponViewEntity : EntityBase
    {
		public virtual string CinemaCode { get; set; }
		public virtual string OpenID { get; set; }
		public virtual decimal? Price { get; set; }
		public virtual string ConponCode { get; set; }
		public virtual DateTime? ValidityDate { get; set; }
		public virtual ConponStatusEnum Status { get; set; }
		public virtual DateTime? UseDate { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string NickName { get; set; }
		public virtual int Id { get; set; }
		public virtual string Title { get; set; }
		public virtual string Image { get; set; }
		public virtual string ConponTypeCode { get; set; }
		public virtual string ConponTypeName { get; set; }
		public virtual int? ConponTypeParentId { get; set; }
		public virtual string SnackCode { get; set; }
		public virtual DateTime? ReceivedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ConponType table.
    /// </summary>
    [Table("ConponType")]
    [SqlLamTable(Name = "ConponType")]
    public partial class ConponTypeEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string TypeName { get; set; }
		public virtual int? TypeParentId { get; set; }
		public virtual string Remark { get; set; }
		public virtual bool IsDel { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
	}

    /// <summary>
    /// A class which represents the SnackOrderDetails table.
    /// </summary>
    [Table("SnackOrderDetails")]
    [SqlLamTable(Name = "SnackOrderDetails")]
    public partial class SnackOrderDetailEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual int OrderId { get; set; }
		public virtual string SnackCode { get; set; }
		public virtual decimal StandardPrice { get; set; }
		public virtual decimal SalePrice { get; set; }
		public virtual int Number { get; set; }
		public virtual decimal SubTotalPrice { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool? Deleted { get; set; }
		public virtual string ConponCode { get; set; }
		public virtual decimal? ConponPrice { get; set; }
		public virtual decimal? ActualPrice { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaPaymentSettings table.
    /// </summary>
    [Table("CinemaPaymentSettings")]
    [SqlLamTable(Name = "CinemaPaymentSettings")]
    public partial class CinemaPaymentSettingEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual YesOrNoEnum IsUseAlipay { get; set; }
		public virtual string AlipaySellerEmail { get; set; }
		public virtual string AlipayPartner { get; set; }
		public virtual string AlipayKey { get; set; }
		public virtual string AlipayAPPID { get; set; }
		public virtual YesOrNoEnum IsUseBfbpay { get; set; }
		public virtual string BfbpaySpno { get; set; }
		public virtual string BfbpayKey { get; set; }
		public virtual YesOrNoEnum IsUseWxpay { get; set; }
		public virtual string WxpayMchId { get; set; }
		public virtual string WxpayKey { get; set; }
		public virtual string WxpayRefundCert { get; set; }
		public virtual YesOrNoEnum IsUserMemberCard { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaPrePaySettings table.
    /// </summary>
    [Table("CinemaPrePaySettings")]
    [SqlLamTable(Name = "CinemaPrePaySettings")]
    public partial class CinemaPrePaySettingEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual YesOrNoEnum IsPrePay { get; set; }
		public virtual decimal? SurplusPayment { get; set; }
		public virtual decimal? LowestPrePayment { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the MemberCardChargeRecords table.
    /// </summary>
    [Table("MemberCardChargeRecords")]
    [SqlLamTable(Name = "MemberCardChargeRecords")]
    public partial class MemberCardChargeRecordEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual int? MemberCardId { get; set; }
		public virtual string CardNo { get; set; }
		public virtual PayTypeEnum? ChargeType { get; set; }
		public virtual decimal? ChargeAmount { get; set; }
		public virtual string ChargeOrderCode { get; set; }
		public virtual string TradeNo { get; set; }
		public virtual bool? Status { get; set; }
		public virtual DateTime? Created { get; set; }
	}

    /// <summary>
    /// A class which represents the SnackOrders table.
    /// </summary>
    [Table("SnackOrders")]
    [SqlLamTable(Name = "SnackOrders")]
    public partial class SnackOrderEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string OrderCode { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual int SnacksCount { get; set; }
		public virtual decimal TotalPrice { get; set; }
		public virtual DateTime? ReleaseTime { get; set; }
		public virtual DateTime? SubmitTime { get; set; }
		public virtual string VoucherCode { get; set; }
		public virtual SnackOrderStatusEnum OrderStatus { get; set; }
		public virtual DateTime? RefundTime { get; set; }
		public virtual DateTime? FetchTime { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime AutoUnLockDateTime { get; set; }
		public virtual string DeliveryAddress { get; set; }
		public virtual DateTime SendTime { get; set; }
		public virtual bool? OrderPayFlag { get; set; }
		public virtual PayTypeEnum? OrderPayType { get; set; }
		public virtual DateTime? OrderPayTime { get; set; }
		public virtual string OrderTradeNo { get; set; }
		public virtual bool? IsUseConpons { get; set; }
		public virtual string ConponCode { get; set; }
		public virtual decimal? ConponPrice { get; set; }
		public virtual string OpenID { get; set; }
	}

    /// <summary>
    /// A class which represents the UserCinemaView view.
    /// </summary>
    [Table("UserCinemaView")]
    [SqlLamTable(Name = "UserCinemaView")]
    public partial class UserCinemaViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual int UserId { get; set; }
		public virtual DateTime? ExpDate { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string PayType { get; set; }
		public virtual SnackInterfaceEnum OpenSnacks { get; set; }
		public virtual decimal? Fee { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string CinemaAddress { get; set; }
		public virtual int? DingXinId { get; set; }
		public virtual string YueKeId { get; set; }
		public virtual string DY1905Id { get; set; }
		public virtual byte CinemaOpen { get; set; }
		public virtual CinemaTypeEnum CinemaType { get; set; }
		public virtual string Url { get; set; }
		public virtual string DefaultUserName { get; set; }
		public virtual string DefaultPassword { get; set; }
	}

    /// <summary>
    /// A class which represents the CinemaTicketSystemAccounts table.
    /// </summary>
    [Table("CinemaTicketSystemAccounts")]
    [SqlLamTable(Name = "CinemaTicketSystemAccounts")]
    public partial class CinemaTicketSystemAccountEntity : EntityBase
    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string Url { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string PayType { get; set; }
		public virtual CinemaTypeEnum TicketSystem { get; set; }
		public virtual bool IsDel { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminOrderView view.
    /// </summary>
    [Table("AdminOrderView")]
    [SqlLamTable(Name = "AdminOrderView")]
    public partial class AdminOrderViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CinemaCode { get; set; }
		public virtual int UserId { get; set; }
		public virtual string SessionCode { get; set; }
		public virtual string ScreenCode { get; set; }
		public virtual DateTime SessionTime { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual int TicketCount { get; set; }
		public virtual decimal TotalPrice { get; set; }
		public virtual decimal TotalFee { get; set; }
		public virtual decimal TotalSalePrice { get; set; }
		public virtual OrderStatusEnum OrderStatus { get; set; }
		public virtual string MobilePhone { get; set; }
		public virtual DateTime? LockTime { get; set; }
		public virtual DateTime? AutoUnlockDatetime { get; set; }
		public virtual string LockOrderCode { get; set; }
		public virtual DateTime? SubmitTime { get; set; }
		public virtual string SubmitOrderCode { get; set; }
		public virtual string PrintNo { get; set; }
		public virtual string VerifyCode { get; set; }
		public virtual byte? PrintStatus { get; set; }
		public virtual DateTime? PrintTime { get; set; }
		public virtual DateTime? RefundTime { get; set; }
		public virtual DateTime Created { get; set; }
		public virtual DateTime? Updated { get; set; }
		public virtual bool Deleted { get; set; }
		public virtual string ErrorMessage { get; set; }
		public virtual string SerialNum { get; set; }
		public virtual bool IsMemberPay { get; set; }
		public virtual string PayType { get; set; }
		public virtual string Printpassword { get; set; }
		public virtual string PaySeqNo { get; set; }
		public virtual string IDCardNumber { get; set; }
		public virtual string CinemaName { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminScreenView view.
    /// </summary>
    [Table("AdminScreenView")]
    [SqlLamTable(Name = "AdminScreenView")]
    public partial class AdminScreenViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CCode { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string SCode { get; set; }
		public virtual string SName { get; set; }
		public virtual DateTime? UpdateTime { get; set; }
		public virtual int? SeatCount { get; set; }
		public virtual string Type { get; set; }
	}

    /// <summary>
    /// A class which represents the AdminSessionView view.
    /// </summary>
    [Table("AdminSessionView")]
    [SqlLamTable(Name = "AdminSessionView")]
    public partial class AdminSessionViewEntity : EntityBase
    {
		public virtual int Id { get; set; }
		public virtual string CCode { get; set; }
		public virtual string SCode { get; set; }
		public virtual string ScreenCode { get; set; }
		public virtual DateTime StartTime { get; set; }
		public virtual string FilmCode { get; set; }
		public virtual string FilmName { get; set; }
		public virtual int? Duration { get; set; }
		public virtual string Language { get; set; }
		public virtual DateTime? UpdateTime { get; set; }
		public virtual decimal StandardPrice { get; set; }
		public virtual decimal LowestPrice { get; set; }
		public virtual bool? IsAvalible { get; set; }
		public virtual string PlaythroughFlag { get; set; }
		public virtual string Dimensional { get; set; }
		public virtual int Sequence { get; set; }
		public virtual int UserID { get; set; }
		public virtual string DingXinUpdateTime { get; set; }
		public virtual decimal? ListingPrice { get; set; }
		public virtual string FeatureNo { get; set; }
		public virtual string CinemaName { get; set; }
		public virtual string ScreenName { get; set; }
		public virtual int? PricePlanID { get; set; }
		public virtual PricePlanTypeEnum? PricePlanType { get; set; }
		public virtual decimal? PricePlanPrice { get; set; }
	}

}
