//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinTicketSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeiXinTicketSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/admin/script 的本地化字符串。
        /// </summary>
        public static string ADMIN_SCRIPT {
            get {
                return ResourceManager.GetString("ADMIN_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/admin/style 的本地化字符串。
        /// </summary>
        public static string ADMIN_STYLE {
            get {
                return ResourceManager.GetString("ADMIN_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/adminLTE/script 的本地化字符串。
        /// </summary>
        public static string ADMINLTE_SCRIPT {
            get {
                return ResourceManager.GetString("ADMINLTE_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/adminLTE/style 的本地化字符串。
        /// </summary>
        public static string ADMINLTE_STYLE {
            get {
                return ResourceManager.GetString("ADMINLTE_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/bootstrap/script 的本地化字符串。
        /// </summary>
        public static string BOOTSTRAP_SCRIPT {
            get {
                return ResourceManager.GetString("BOOTSTRAP_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/bootstrap/style 的本地化字符串。
        /// </summary>
        public static string BOOTSTRAP_STYLE {
            get {
                return ResourceManager.GetString("BOOTSTRAP_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/datepicker/script 的本地化字符串。
        /// </summary>
        public static string DATEPICKER_SCRIPT {
            get {
                return ResourceManager.GetString("DATEPICKER_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/datepicker/style 的本地化字符串。
        /// </summary>
        public static string DATEPICKER_STYLE {
            get {
                return ResourceManager.GetString("DATEPICKER_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/daterangepicker/script 的本地化字符串。
        /// </summary>
        public static string DATERANGEPICKER_SCRIPT {
            get {
                return ResourceManager.GetString("DATERANGEPICKER_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/daterangepicker/style 的本地化字符串。
        /// </summary>
        public static string DATERANGEPICKER_STYLE {
            get {
                return ResourceManager.GetString("DATERANGEPICKER_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string DEFAULT_CINEMACODE {
            get {
                return ResourceManager.GetString("DEFAULT_CINEMACODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/dynatable/script 的本地化字符串。
        /// </summary>
        public static string DYNATABLE_SCRIPT {
            get {
                return ResourceManager.GetString("DYNATABLE_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/dynatable/style 的本地化字符串。
        /// </summary>
        public static string DYNATABLE_STYLE {
            get {
                return ResourceManager.GetString("DYNATABLE_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/font-awesome 的本地化字符串。
        /// </summary>
        public static string FONT_AWESOME {
            get {
                return ResourceManager.GetString("FONT_AWESOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/handlebars 的本地化字符串。
        /// </summary>
        public static string HANDLEBARS {
            get {
                return ResourceManager.GetString("HANDLEBARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/icheck/script 的本地化字符串。
        /// </summary>
        public static string ICHECK_SCRIPT {
            get {
                return ResourceManager.GetString("ICHECK_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/icheck/style 的本地化字符串。
        /// </summary>
        public static string ICHECK_STYLE {
            get {
                return ResourceManager.GetString("ICHECK_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/jquery 的本地化字符串。
        /// </summary>
        public static string JQUERY {
            get {
                return ResourceManager.GetString("JQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/morris/script 的本地化字符串。
        /// </summary>
        public static string MORRIS_SCRIPT {
            get {
                return ResourceManager.GetString("MORRIS_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/morris/style 的本地化字符串。
        /// </summary>
        public static string MORRIS_STYLE {
            get {
                return ResourceManager.GetString("MORRIS_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/notify/script 的本地化字符串。
        /// </summary>
        public static string NOTIFY_SCRIPT {
            get {
                return ResourceManager.GetString("NOTIFY_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/notify/style 的本地化字符串。
        /// </summary>
        public static string NOTIFY_STYLE {
            get {
                return ResourceManager.GetString("NOTIFY_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/select2/script 的本地化字符串。
        /// </summary>
        public static string SELECT2_SCRIPT {
            get {
                return ResourceManager.GetString("SELECT2_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~/bundles/select2/style 的本地化字符串。
        /// </summary>
        public static string SELECT2_STYLE {
            get {
                return ResourceManager.GetString("SELECT2_STYLE", resourceCulture);
            }
        }
    }
}
